### ISSUE TITLE
Feature: Add data source category (C__CATG__IDENTIFIER)

### ISSUE THREAD

**Issue by xschlef** [ScaleUp-Technologies/ansible-i-doit#1]
Hi,

we are trying to utilize your ansible modules and we are relying heavily on the data source category to synchronize different data sources. Is it possible that you implement DataSource (C__CATG__IDENTIFIER) as additional module? The category is named "Custom Identifier" in german. Quite misleading...

Maybe I can add a PR in a few days.

Thanks

**Comment by fzakfeld** [comment]
Hi @xschlef - I'll try to add that in the upcoming days. We are also documenting a way to easily create your own version of the plugin with any custom categories - although the non-custom ones like C__CATG__IDENTIFIER should definitely be in the public repo.

**Comment by tabacha** [comment]
Hi 
we have added  C__CATG__IDENTIFIER in Version 0.14.0. But we can not push the version to Ansible-Galays, cause of:
https://github.com/ansible/galaxy/issues/3267

As workaround you can install this version via:
```
git clone https://github.com/ScaleUp-Technologies/ansible-i-doit/
cd ansible-i-doit
git checkout v0.14.0
MYTMP=$(mktemp -d)
python3 build.py
ansible-galaxy collection build --output-path ${MYTMP}
ansible-galaxy collection install --force ${MYTMP}/*.tar.gz
rm -rf ${MYTMP}
```

**Comment by tabacha** [comment]
Hi, we just uploaded the version 0.20.0 which will contains  https://galaxy.ansible.com/ui/repo/published/scaleuptechnologies/idoit/content/module/idoit_cat_identifier/ and https://galaxy.ansible.com/ui/repo/published/scaleuptechnologies/idoit/content/module/idoit_cat_identifier_info/
